### PR TITLE
allow to build on linux

### PR DESCRIPTION
**Pull request by TurBoss**
this patch allows to build on linux without having 2 main files

### CODE REVIEW

**Comment by TurBoss** [comment]
this goes for #17

**Comment by TurBoss** [comment]
oops closed?

**Comment by EVILEDLIBRE** [comment]
I would like this to work also. Until it is included, how do I compile with two main files? I've never heard of that before. When I fallow the instructions for compiling as given on the main page, it keeps giving me errors.

**Comment by TurBoss** [comment]
just run build.sh or build.bat

**Pull request closed without merging**
